export const inputProps = [
	{
		name: 'modelValue',
		type: 'string | number | null',
		default: "''",
		description: 'apiReferenceDescriptions.inputModelValue',
	},
	{
		name: 'id',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputId',
	},
	{
		name: 'label',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.floatingLabel',
	},
	{
		name: 'type',
		type: "'text' | 'email' | 'password' | 'tel' | 'url' | 'number'",
		default: "'text'",
		description: 'apiReferenceDescriptions.inputType',
	},
	{
		name: 'placeholder',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputPlaceholder',
	},
	{
		name: 'autocomplete',
		type: "'on' | 'off'",
		default: '-',
		description: 'apiReferenceDescriptions.inputAutocomplete',
	},
	{
		name: 'autofocus',
		type: 'boolean',
		default: 'false',
		description: 'apiReferenceDescriptions.inputAutoFocus',
	},
	{
		name: 'required',
		type: 'boolean',
		default: 'false',
		description: 'apiReferenceDescriptions.inputRequired',
	},
	{
		name: 'min',
		type: 'number',
		default: '-',
		description: 'apiReferenceDescriptions.inputMin',
	},
	{
		name: 'max',
		type: 'number',
		default: '-',
		description: 'apiReferenceDescriptions.inputMax',
	},
	{
		name: 'pattern',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputPattern',
	},
	{
		name: 'patternMessage',
		type: 'string',
		default: "'Некорректный формат'",
		description: 'apiReferenceDescriptions.patternMessage',
	},
	{
		name: 'mask',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputMask',
	},
	{
		name: 'hint',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputHint',
	},
	{
		name: 'error',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputError',
	},
	{
		name: 'disabled',
		type: 'boolean',
		default: 'false',
		description: 'apiReferenceDescriptions.inputDisabled',
	},
	{
		name: 'readonly',
		type: 'boolean',
		default: 'false',
		description: 'apiReferenceDescriptions.inputReadonly',
	},
	{
		name: 'hasClearButton',
		type: 'boolean',
		default: 'true',
		description: 'apiReferenceDescriptions.inputClearButton',
	},
];
