export const inputProps = [
	{
		name: 'control',
		type: 'XControl<string | number | null>',
		default: '-',
		description: 'apiReferenceDescriptions.inputControl',
	},
	{
		name: 'id',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputId',
	},
	{
		name: 'label',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.floatingLabel',
	},
	{
		name: 'type',
		type: "'text' | 'email' | 'password' | 'tel' | 'url' | 'number'",
		default: "'text'",
		description: 'apiReferenceDescriptions.inputType',
	},
	{
		name: 'placeholder',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputPlaceholder',
	},
	{
		name: 'autocomplete',
		type: "'on' | 'off'",
		default: '-',
		description: 'apiReferenceDescriptions.inputAutocomplete',
	},
	{
		name: 'autofocus',
		type: 'boolean',
		default: 'false',
		description: 'apiReferenceDescriptions.inputAutoFocus',
	},
	{
		name: 'required',
		type: 'boolean',
		default: 'false',
		description: 'apiReferenceDescriptions.inputRequired',
	},
	{
		name: 'min',
		type: 'number',
		default: '-',
		description: 'apiReferenceDescriptions.inputMin',
	},
	{
		name: 'max',
		type: 'number',
		default: '-',
		description: 'apiReferenceDescriptions.inputMax',
	},
	{
		name: 'pattern',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputPattern',
	},
	{
		name: 'patternMessage',
		type: 'string',
		default: "'validation.pattern'",
		description: 'apiReferenceDescriptions.patternMessage',
	},
	{
		name: 'mask',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputMask',
	},
	{
		name: 'hint',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputHint',
	},
	{
		name: 'error',
		type: 'string',
		default: '-',
		description: 'apiReferenceDescriptions.inputError',
	},
	{
		name: 'disabled',
		type: 'boolean',
		default: 'false',
		description: 'apiReferenceDescriptions.inputDisabled',
	},
	{
		name: 'readonly',
		type: 'boolean',
		default: 'false',
		description: 'apiReferenceDescriptions.inputReadonly',
	},
	{
		name: 'hasClearButton',
		type: 'boolean',
		default: 'true',
		description: 'apiReferenceDescriptions.inputClearButton',
	},
];

export const xControlApiRows = [
	{
		name: 'value',
		type: 'T',
		default: '-',
		description: 'apiReferenceDescriptions.xControlValue',
	},
	{
		name: 'errors',
		type: 'Record<string, string>',
		default: '{}',
		description: 'apiReferenceDescriptions.inputErrors',
	},
	{
		name: 'valid / invalid',
		type: 'boolean',
		default: 'true / false',
		description: 'apiReferenceDescriptions.xControlValidity',
	},
	{
		name: 'touched / untouched',
		type: 'boolean',
		default: 'false / true',
		description: 'apiReferenceDescriptions.xControlTouched',
	},
	{
		name: 'dirty / pristine',
		type: 'boolean',
		default: 'false / true',
		description: 'apiReferenceDescriptions.xControlDirty',
	},
	{
		name: 'disabled / enabled',
		type: 'boolean',
		default: 'false / true',
		description: 'apiReferenceDescriptions.xControlDisabled',
	},
	{
		name: 'setValue(value)',
		type: '(value: T) => void',
		default: '-',
		description: 'apiReferenceDescriptions.xControlSetValue',
	},
	{
		name: 'reset(value?)',
		type: '(value?: T) => void',
		default: '-',
		description: 'apiReferenceDescriptions.xControlReset',
	},
	{
		name: 'validate()',
		type: '() => boolean',
		default: '-',
		description: 'apiReferenceDescriptions.inputValidate',
	},
	{
		name: 'hasError(key)',
		type: '(key: string) => boolean',
		default: '-',
		description: 'apiReferenceDescriptions.inputHasError',
	},
	{
		name: 'disable() / enable()',
		type: '() => void',
		default: '-',
		description: 'apiReferenceDescriptions.xControlToggleDisabled',
	},
];
